baseurl: https://hishark777.com/
languageCode: en-us
theme: hugo-theme-stack
paginate: 15
title: á•)à­¨ ä¹¾æ¯ # à­¨ã¤ãƒ­ 

# blackfriday:
#     extensionsmask: ["noIntraEmphasis"]
#     fractions: false

# markup:
#     goldmark:
#         renderer:
#             unsafe: true

# Change it to your Disqus shortname before using
disqusShortname: 

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    # post: /p/:slug/
    post: "/post/:filename/"
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2017
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: ðŸ§¸
        subtitle: '> $ cd /777/blog'
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo: https://github.com/hishark/hishark.github.io
            issueTerm: pathname
            label: comment
            theme: preferred-color-scheme

    widgets:
        enabled:
            # - search
            # - archives
            # - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: hishark777

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true


menu:
    main:
        - identifier: posts
          name: Posts
          url: /post
          weight: 1
          pre: infinity

        - identifier: about
          name: About
          url: about
          weight: 2
          pre: user

        # - identifier: tags
        #   name: Tags
        #   url: tags
        #   weight: -90
        #   pre: tag

        

        - identifier: archives
          name: Timeline
          url: archives
          weight: 3
          pre: clock

        - identifier: search
          name: Search
          url: search
          weight: 4
          pre: search

        - identifier: album
          name: Photos
          url: https://www.douban.com/people/hishark/photos
          weight: 5
          pre: album

        - identifier: github
          name: Github
          url: https://github.com/hishark
          weight: 5
          pre: github

        - identifier: linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/zhangxiaoqi
          weight: 5
          pre: linkedin

        - identifier: Notes
          name: Interview Notes
          url: https://hishark777.gitbook.io/777-interview-notes/
          weight: 6
          pre: notes

#   # Social icons
#   [[params.social]]
#     name = "twitter"
#     url  = "https://twitter.com/hishark777"

#   [[params.social]]
#     name = "instagram"
#     url  = "https://www.instagram.com/hishark777"

#   [[params.social]]
#     name = "email"
#     url  = "mailto:hishark777@gmail.com"

#   [[params.social]]
#     name = "github"
#     url  = ""

#   [[params.social]]
#     name = "telegram"
#     url  = "https://t.me/hishark777"

#   [[params.social]]
#     name = "linkedin"
#     url  = ""


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
